#!/bin/sh
#
# Start serial....
#

cd $CONFIGFS_HOME/usb_gadget

case "$1" in
  start)
	echo "Starting usb serial devices ..."

	mkdir -p demo/functions/gser.0
	if [ $? != 0 ]; then
		echo "unable to create function serial, check kernel config!"
		exit 1
	fi
	ln -s demo/functions/gser.0 demo/configs/c.1/

	;;
  stop)
	echo "Stop usb serial devices ..."
	if [ ! -d demo/configs/c.1/gser.0 ];then
		exit 0
	fi

	rm demo/configs/c.1/gser.0
	rm demo/functions/gser.0

	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
exit $?
