#!/bin/sh

case "$1" in
  start)
	rm -rf /usr/data/ota_res
	cp -r /etc/ota_res/ /usr/data/
	cp -r /firmware/ /usr/data/
	cp /usr/bin/fbshow /usr/data/
	#cp /usr/bin/bsa_server_mips /usr/data/
	#cp /usr/sbin/wpa_supplicant /usr/data/
	#cp /etc/wpa_supplicant.conf /usr/data/
	cp /usr/lib/libsysutils.so /usr/data/
	cp /usr/lib/libcutils.so /usr/data/
	cp /usr/lib/libstdc++.so.6.0.24 /usr/data/
	cp /usr/lib/libjpeg.so.8.2.2 /usr/data/
	sync
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

